// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/envoy/v12/http/grpc_metadata_scrubber/config.proto

package grpc_metadata_scrubber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FilterConfig) Reset() {
	*x = FilterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterConfig) ProtoMessage() {}

func (x *FilterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterConfig.ProtoReflect.Descriptor instead.
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDescGZIP(), []int{0}
}

var File_api_envoy_v12_http_grpc_metadata_scrubber_config_proto protoreflect.FileDescriptor

var file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDesc = []byte{
	0x0a, 0x36, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x76, 0x31, 0x32, 0x2f,
	0x68, 0x74, 0x74, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x73, 0x63, 0x72, 0x75, 0x62, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2f, 0x65, 0x73, 0x70, 0x76, 0x32, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x76, 0x31, 0x32, 0x2e, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x73, 0x63, 0x72, 0x75, 0x62, 0x62, 0x65, 0x72, 0x22, 0x0e, 0x0a, 0x0c, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDescOnce sync.Once
	file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDescData = file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDesc
)

func file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDescGZIP() []byte {
	file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDescOnce.Do(func() {
		file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDescData)
	})
	return file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDescData
}

var file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_goTypes = []interface{}{
	(*FilterConfig)(nil), // 0: espv2.api.envoy.v12.http.grpc_metadata_scrubber.FilterConfig
}
var file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_init() }
func file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_init() {
	if File_api_envoy_v12_http_grpc_metadata_scrubber_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_goTypes,
		DependencyIndexes: file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_depIdxs,
		MessageInfos:      file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_msgTypes,
	}.Build()
	File_api_envoy_v12_http_grpc_metadata_scrubber_config_proto = out.File
	file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_rawDesc = nil
	file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_goTypes = nil
	file_api_envoy_v12_http_grpc_metadata_scrubber_config_proto_depIdxs = nil
}
