// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/envoy/v12/http/path_rewrite/config.proto

package path_rewrite

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConstantPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	UrlTemplate string `protobuf:"bytes,2,opt,name=url_template,json=urlTemplate,proto3" json:"url_template,omitempty"`
}

func (x *ConstantPath) Reset() {
	*x = ConstantPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstantPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstantPath) ProtoMessage() {}

func (x *ConstantPath) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstantPath.ProtoReflect.Descriptor instead.
func (*ConstantPath) Descriptor() ([]byte, []int) {
	return file_api_envoy_v12_http_path_rewrite_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConstantPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConstantPath) GetUrlTemplate() string {
	if x != nil {
		return x.UrlTemplate
	}
	return ""
}

type PerRouteFilterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to PathTranslationSpecifier:
	//	*PerRouteFilterConfig_PathPrefix
	//	*PerRouteFilterConfig_ConstantPath
	PathTranslationSpecifier isPerRouteFilterConfig_PathTranslationSpecifier `protobuf_oneof:"path_translation_specifier"`
}

func (x *PerRouteFilterConfig) Reset() {
	*x = PerRouteFilterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerRouteFilterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerRouteFilterConfig) ProtoMessage() {}

func (x *PerRouteFilterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerRouteFilterConfig.ProtoReflect.Descriptor instead.
func (*PerRouteFilterConfig) Descriptor() ([]byte, []int) {
	return file_api_envoy_v12_http_path_rewrite_config_proto_rawDescGZIP(), []int{1}
}

func (m *PerRouteFilterConfig) GetPathTranslationSpecifier() isPerRouteFilterConfig_PathTranslationSpecifier {
	if m != nil {
		return m.PathTranslationSpecifier
	}
	return nil
}

func (x *PerRouteFilterConfig) GetPathPrefix() string {
	if x, ok := x.GetPathTranslationSpecifier().(*PerRouteFilterConfig_PathPrefix); ok {
		return x.PathPrefix
	}
	return ""
}

func (x *PerRouteFilterConfig) GetConstantPath() *ConstantPath {
	if x, ok := x.GetPathTranslationSpecifier().(*PerRouteFilterConfig_ConstantPath); ok {
		return x.ConstantPath
	}
	return nil
}

type isPerRouteFilterConfig_PathTranslationSpecifier interface {
	isPerRouteFilterConfig_PathTranslationSpecifier()
}

type PerRouteFilterConfig_PathPrefix struct {
	PathPrefix string `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3,oneof"`
}

type PerRouteFilterConfig_ConstantPath struct {
	ConstantPath *ConstantPath `protobuf:"bytes,2,opt,name=constant_path,json=constantPath,proto3,oneof"`
}

func (*PerRouteFilterConfig_PathPrefix) isPerRouteFilterConfig_PathTranslationSpecifier() {}

func (*PerRouteFilterConfig_ConstantPath) isPerRouteFilterConfig_PathTranslationSpecifier() {}

type FilterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FilterConfig) Reset() {
	*x = FilterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterConfig) ProtoMessage() {}

func (x *FilterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterConfig.ProtoReflect.Descriptor instead.
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return file_api_envoy_v12_http_path_rewrite_config_proto_rawDescGZIP(), []int{2}
}

var File_api_envoy_v12_http_path_rewrite_config_proto protoreflect.FileDescriptor

var file_api_envoy_v12_http_path_rewrite_config_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x76, 0x31, 0x32, 0x2f,
	0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25,
	0x65, 0x73, 0x70, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e,
	0x76, 0x31, 0x32, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x72, 0x65,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f,
	0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2c,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xfa, 0x42,
	0x15, 0x72, 0x13, 0x10, 0x01, 0x32, 0x0f, 0x5e, 0x5b, 0x5e, 0x3f, 0x26, 0x23, 0x5c, 0x72, 0x5c,
	0x6e, 0x5c, 0x30, 0x5d, 0x2b, 0x24, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c,
	0x75, 0x72, 0x6c, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x75, 0x72, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22,
	0xd2, 0x01, 0x0a, 0x14, 0x50, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3b, 0x0a, 0x0b, 0x70, 0x61, 0x74, 0x68,
	0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xfa,
	0x42, 0x15, 0x72, 0x13, 0x10, 0x02, 0x32, 0x0f, 0x5e, 0x5b, 0x5e, 0x3f, 0x26, 0x23, 0x5c, 0x72,
	0x5c, 0x6e, 0x5c, 0x30, 0x5d, 0x2b, 0x24, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x61, 0x74, 0x68, 0x50,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x5a, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x65,
	0x73, 0x70, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x76,
	0x31, 0x32, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x48, 0x00, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x42, 0x21, 0x0a, 0x1a, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12,
	0x03, 0xf8, 0x42, 0x01, 0x22, 0x0e, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_envoy_v12_http_path_rewrite_config_proto_rawDescOnce sync.Once
	file_api_envoy_v12_http_path_rewrite_config_proto_rawDescData = file_api_envoy_v12_http_path_rewrite_config_proto_rawDesc
)

func file_api_envoy_v12_http_path_rewrite_config_proto_rawDescGZIP() []byte {
	file_api_envoy_v12_http_path_rewrite_config_proto_rawDescOnce.Do(func() {
		file_api_envoy_v12_http_path_rewrite_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_envoy_v12_http_path_rewrite_config_proto_rawDescData)
	})
	return file_api_envoy_v12_http_path_rewrite_config_proto_rawDescData
}

var file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_envoy_v12_http_path_rewrite_config_proto_goTypes = []interface{}{
	(*ConstantPath)(nil),         // 0: espv2.api.envoy.v12.http.path_rewrite.ConstantPath
	(*PerRouteFilterConfig)(nil), // 1: espv2.api.envoy.v12.http.path_rewrite.PerRouteFilterConfig
	(*FilterConfig)(nil),         // 2: espv2.api.envoy.v12.http.path_rewrite.FilterConfig
}
var file_api_envoy_v12_http_path_rewrite_config_proto_depIdxs = []int32{
	0, // 0: espv2.api.envoy.v12.http.path_rewrite.PerRouteFilterConfig.constant_path:type_name -> espv2.api.envoy.v12.http.path_rewrite.ConstantPath
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_envoy_v12_http_path_rewrite_config_proto_init() }
func file_api_envoy_v12_http_path_rewrite_config_proto_init() {
	if File_api_envoy_v12_http_path_rewrite_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstantPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerRouteFilterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PerRouteFilterConfig_PathPrefix)(nil),
		(*PerRouteFilterConfig_ConstantPath)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_envoy_v12_http_path_rewrite_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_envoy_v12_http_path_rewrite_config_proto_goTypes,
		DependencyIndexes: file_api_envoy_v12_http_path_rewrite_config_proto_depIdxs,
		MessageInfos:      file_api_envoy_v12_http_path_rewrite_config_proto_msgTypes,
	}.Build()
	File_api_envoy_v12_http_path_rewrite_config_proto = out.File
	file_api_envoy_v12_http_path_rewrite_config_proto_rawDesc = nil
	file_api_envoy_v12_http_path_rewrite_config_proto_goTypes = nil
	file_api_envoy_v12_http_path_rewrite_config_proto_depIdxs = nil
}
