// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/envoy/v12/http/backend_auth/config.proto

package backend_auth

import (
	common "github.com/GoogleCloudPlatform/esp-v2/src/go/proto/api/envoy/v12/http/common"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PerRouteFilterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtAudience string `protobuf:"bytes,1,opt,name=jwt_audience,json=jwtAudience,proto3" json:"jwt_audience,omitempty"`
}

func (x *PerRouteFilterConfig) Reset() {
	*x = PerRouteFilterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_envoy_v12_http_backend_auth_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerRouteFilterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerRouteFilterConfig) ProtoMessage() {}

func (x *PerRouteFilterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_v12_http_backend_auth_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerRouteFilterConfig.ProtoReflect.Descriptor instead.
func (*PerRouteFilterConfig) Descriptor() ([]byte, []int) {
	return file_api_envoy_v12_http_backend_auth_config_proto_rawDescGZIP(), []int{0}
}

func (x *PerRouteFilterConfig) GetJwtAudience() string {
	if x != nil {
		return x.JwtAudience
	}
	return ""
}

type FilterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtAudienceList []string `protobuf:"bytes,1,rep,name=jwt_audience_list,json=jwtAudienceList,proto3" json:"jwt_audience_list,omitempty"`
	// Types that are assignable to IdTokenInfo:
	//	*FilterConfig_ImdsToken
	//	*FilterConfig_IamToken
	IdTokenInfo      isFilterConfig_IdTokenInfo     `protobuf_oneof:"id_token_info"`
	DepErrorBehavior common.DependencyErrorBehavior `protobuf:"varint,4,opt,name=dep_error_behavior,json=depErrorBehavior,proto3,enum=espv2.api.envoy.v12.http.common.DependencyErrorBehavior" json:"dep_error_behavior,omitempty"`
}

func (x *FilterConfig) Reset() {
	*x = FilterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_envoy_v12_http_backend_auth_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterConfig) ProtoMessage() {}

func (x *FilterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_v12_http_backend_auth_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterConfig.ProtoReflect.Descriptor instead.
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return file_api_envoy_v12_http_backend_auth_config_proto_rawDescGZIP(), []int{1}
}

func (x *FilterConfig) GetJwtAudienceList() []string {
	if x != nil {
		return x.JwtAudienceList
	}
	return nil
}

func (m *FilterConfig) GetIdTokenInfo() isFilterConfig_IdTokenInfo {
	if m != nil {
		return m.IdTokenInfo
	}
	return nil
}

func (x *FilterConfig) GetImdsToken() *common.HttpUri {
	if x, ok := x.GetIdTokenInfo().(*FilterConfig_ImdsToken); ok {
		return x.ImdsToken
	}
	return nil
}

func (x *FilterConfig) GetIamToken() *common.IamTokenInfo {
	if x, ok := x.GetIdTokenInfo().(*FilterConfig_IamToken); ok {
		return x.IamToken
	}
	return nil
}

func (x *FilterConfig) GetDepErrorBehavior() common.DependencyErrorBehavior {
	if x != nil {
		return x.DepErrorBehavior
	}
	return common.DependencyErrorBehavior(0)
}

type isFilterConfig_IdTokenInfo interface {
	isFilterConfig_IdTokenInfo()
}

type FilterConfig_ImdsToken struct {
	ImdsToken *common.HttpUri `protobuf:"bytes,2,opt,name=imds_token,json=imdsToken,proto3,oneof"`
}

type FilterConfig_IamToken struct {
	IamToken *common.IamTokenInfo `protobuf:"bytes,3,opt,name=iam_token,json=iamToken,proto3,oneof"`
}

func (*FilterConfig_ImdsToken) isFilterConfig_IdTokenInfo() {}

func (*FilterConfig_IamToken) isFilterConfig_IdTokenInfo() {}

var File_api_envoy_v12_http_backend_auth_config_proto protoreflect.FileDescriptor

var file_api_envoy_v12_http_backend_auth_config_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x76, 0x31, 0x32, 0x2f,
	0x68, 0x74, 0x74, 0x70, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x75, 0x74,
	0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25,
	0x65, 0x73, 0x70, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e,
	0x76, 0x31, 0x32, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79,
	0x2f, 0x76, 0x31, 0x32, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x14, 0x50, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3b, 0x0a, 0x0c,
	0x6a, 0x77, 0x74, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x18, 0xfa, 0x42, 0x15, 0x72, 0x13, 0x20, 0x01, 0x32, 0x0f, 0x5e, 0x5b, 0x5e,
	0x3f, 0x26, 0x23, 0x5c, 0x72, 0x5c, 0x6e, 0x5c, 0x30, 0x5d, 0x2b, 0x24, 0x52, 0x0b, 0x6a, 0x77,
	0x74, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xf2, 0x02, 0x0a, 0x0c, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x4b, 0x0a, 0x11, 0x6a, 0x77,
	0x74, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x1f, 0xfa, 0x42, 0x1c, 0x92, 0x01, 0x19, 0x08, 0x01, 0x22,
	0x15, 0x72, 0x13, 0x10, 0x01, 0x32, 0x0f, 0x5e, 0x5b, 0x5e, 0x3f, 0x26, 0x23, 0x5c, 0x72, 0x5c,
	0x6e, 0x5c, 0x30, 0x5d, 0x2b, 0x24, 0x52, 0x0f, 0x6a, 0x77, 0x74, 0x41, 0x75, 0x64, 0x69, 0x65,
	0x6e, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x0a, 0x69, 0x6d, 0x64, 0x73, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x65, 0x73,
	0x70, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x76, 0x31,
	0x32, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x74,
	0x74, 0x70, 0x55, 0x72, 0x69, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6d, 0x64, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x4c, 0x0a, 0x09, 0x69, 0x61, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x65, 0x73, 0x70, 0x76, 0x32, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x76, 0x31, 0x32, 0x2e, 0x68, 0x74, 0x74, 0x70,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x61, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x69, 0x61, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x66, 0x0a, 0x12, 0x64, 0x65, 0x70, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x62, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x65,
	0x73, 0x70, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x76,
	0x31, 0x32, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x10, 0x64, 0x65, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x42, 0x14, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x03, 0xf8, 0x42, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_envoy_v12_http_backend_auth_config_proto_rawDescOnce sync.Once
	file_api_envoy_v12_http_backend_auth_config_proto_rawDescData = file_api_envoy_v12_http_backend_auth_config_proto_rawDesc
)

func file_api_envoy_v12_http_backend_auth_config_proto_rawDescGZIP() []byte {
	file_api_envoy_v12_http_backend_auth_config_proto_rawDescOnce.Do(func() {
		file_api_envoy_v12_http_backend_auth_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_envoy_v12_http_backend_auth_config_proto_rawDescData)
	})
	return file_api_envoy_v12_http_backend_auth_config_proto_rawDescData
}

var file_api_envoy_v12_http_backend_auth_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_envoy_v12_http_backend_auth_config_proto_goTypes = []interface{}{
	(*PerRouteFilterConfig)(nil),        // 0: espv2.api.envoy.v12.http.backend_auth.PerRouteFilterConfig
	(*FilterConfig)(nil),                // 1: espv2.api.envoy.v12.http.backend_auth.FilterConfig
	(*common.HttpUri)(nil),              // 2: espv2.api.envoy.v12.http.common.HttpUri
	(*common.IamTokenInfo)(nil),         // 3: espv2.api.envoy.v12.http.common.IamTokenInfo
	(common.DependencyErrorBehavior)(0), // 4: espv2.api.envoy.v12.http.common.DependencyErrorBehavior
}
var file_api_envoy_v12_http_backend_auth_config_proto_depIdxs = []int32{
	2, // 0: espv2.api.envoy.v12.http.backend_auth.FilterConfig.imds_token:type_name -> espv2.api.envoy.v12.http.common.HttpUri
	3, // 1: espv2.api.envoy.v12.http.backend_auth.FilterConfig.iam_token:type_name -> espv2.api.envoy.v12.http.common.IamTokenInfo
	4, // 2: espv2.api.envoy.v12.http.backend_auth.FilterConfig.dep_error_behavior:type_name -> espv2.api.envoy.v12.http.common.DependencyErrorBehavior
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_envoy_v12_http_backend_auth_config_proto_init() }
func file_api_envoy_v12_http_backend_auth_config_proto_init() {
	if File_api_envoy_v12_http_backend_auth_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_envoy_v12_http_backend_auth_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerRouteFilterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_envoy_v12_http_backend_auth_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_envoy_v12_http_backend_auth_config_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FilterConfig_ImdsToken)(nil),
		(*FilterConfig_IamToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_envoy_v12_http_backend_auth_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_envoy_v12_http_backend_auth_config_proto_goTypes,
		DependencyIndexes: file_api_envoy_v12_http_backend_auth_config_proto_depIdxs,
		MessageInfos:      file_api_envoy_v12_http_backend_auth_config_proto_msgTypes,
	}.Build()
	File_api_envoy_v12_http_backend_auth_config_proto = out.File
	file_api_envoy_v12_http_backend_auth_config_proto_rawDesc = nil
	file_api_envoy_v12_http_backend_auth_config_proto_goTypes = nil
	file_api_envoy_v12_http_backend_auth_config_proto_depIdxs = nil
}
